### ISSUE TITLE
Chef::Mixin::Template::TemplateError:  (Node attributes are read-only when you do not specify which precedence level to set. 

### ISSUE THREAD

**Issue by dblock** [sunggun-yu/chef-mongodb3#21]
Been trying to figure this one out for a while, at no avail. Help please?

Amazon Linux 2015.09
Chef 11.10

I don't have any custom cookbooks and couldn't find anything assigning anything without a proper `set` or `default`.

```
[2016-01-14T00:13:51+00:00] INFO: Processing template[/etc/mongod.conf] action create (mongodb3::default line 53)

================================================================================
Error executing action `create` on resource 'template[/etc/mongod.conf]'
================================================================================


Chef::Mixin::Template::TemplateError
------------------------------------
Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb3/recipes/default.rb

53: template node['mongodb3']['mongod']['config_file'] do
54:   source 'mongodb.conf.erb'
55:   mode 0644
56:   variables(
57:       :config => node['mongodb3']['config']['mongod']
58:   )
59:   helpers Mongodb3Helper
60: end
61: 



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb3/recipes/default.rb:53:in `from_file'

template("/etc/mongod.conf") do
provider Chef::Provider::Template
action "create"
retries 0
retry_delay 2
path "/etc/mongod.conf"
backup 5
atomic_update true
source "mongodb.conf.erb"
variables {:config=>{"systemLog"=>{"verbosity"=>nil, "quiet"=>nil, "traceAllException"=>nil, "syslogFacility"=>nil, "path"=>"/var/log/mongodb/mongod.log", "logAppend"=>true, "logRotate"=>nil, "destination"=>"file", "timeStampFormat"=>nil, "component"=>{"accessControl"=>{"verbosity"=>nil}, "command"=>{"verbosity"=>nil}, "control"=>{"verbosity"=>nil}, "geo"=>{"verbosity"=>nil}, "index"=>{"verbosity"=>nil}, "network"=>{"verbosity"=>nil}, "query"=>{"verbosity"=>nil}, "replication"=>{"verbosity"=>nil}, "sharding"=>{"verbosity"=>nil}, "storage"=>{"verbosity"=>nil, "journal"=>{"verbosity"=>nil}}, "write"=>{"verbosity"=>nil}}}, "processManagement"=>{"fork"=>true, "pidFilePath"=>"/var/run/mongodb/mongodb.pid"}, "net"=>{"port"=>27017, "bindIp"=>nil, "maxIncomingConnections"=>nil, "wireObjectCheck"=>nil, "ipv6"=>nil, "unixDomainSocket"=>{"enabled"=>nil, "pathPrefix"=>nil, "filePermissions"=>nil}, "http"=>{"enabled"=>nil, "JSONPEnabled"=>nil, "RESTInterfaceEnabled"=>nil}, "ssl"=>{"mode"=>nil, "PEMKeyFile"=>nil, "PEMKeyPassword"=>nil, "clusterFile"=>nil, "clusterPassword"=>nil, "CAFile"=>nil, "CRLFile"=>nil, "allowConnectionsWithoutCertificates"=>nil, "allowInvalidCertificates"=>nil, "allowInvalidHostnames"=>nil, "FIPSMode"=>nil}}, "security"=>{"keyFile"=>nil, "clusterAuthMode"=>nil, "authorization"=>"disabled", "javascriptEnabled"=>nil, "sasl"=>{"hostName"=>nil, "serviceName"=>nil, "saslauthdSocketPath"=>nil}}, "storage"=>{"dbPath"=>"/var/lib/mongo", "indexBuildRetry"=>nil, "repairPath"=>nil, "journal"=>{"enabled"=>true}, "directoryPerDB"=>nil, "syncPeriodSecs"=>nil, "engine"=>"wiredTiger", "mmapv1"=>{"preallocDataFiles"=>nil, "nsSize"=>nil, "quota"=>{"enforced"=>nil, "maxFilesPerDB"=>nil}, "smallFiles"=>nil, "journal"=>{"debugFlags"=>nil, "commitIntervalMs"=>nil}}, "wiredTiger"=>{"engineConfig"=>{"cacheSizeGB"=>nil, "statisticsLogDelaySecs"=>nil, "journalCompressor"=>nil, "directoryForIndexes"=>nil}, "collectionConfig"=>{"blockCompressor"=>nil}, "indexConfig"=>{"prefixCompression"=>nil}}}, "operationProfiling"=>{"slowOpThresholdMs"=>nil, "mode"=>nil}, "replication"=>{"oplogSizeMB"=>nil, "replSetName"=>nil, "secondaryIndexPrefetch"=>nil}, "sharding"=>{"clusterRole"=>nil, "archiveMovedChunks"=>nil}, "auditLog"=>{"destination"=>nil, "format"=>nil, "path"=>nil, "filter"=>nil}, "snmp"=>{"subagent"=>nil, "master"=>nil}}}
helper_modules [Mongodb3Helper]
cookbook_name "mongodb3"
recipe_name "default"
mode 420
end



Template Context:
-----------------
on line #2
1: # THIS FILE IS MAINTAINED BY CHEF. DO NOT MODIFY AS IT WILL BE OVERWRITTEN.
2: <%= mongodb_config @config%>


[2016-01-14T00:13:51+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-01-14T00:13:51+00:00] INFO: template[/etc/redis/6379.conf] sending restart action to service[redis] (delayed)
[2016-01-14T00:13:51+00:00] INFO: Processing service[redis] action restart (redis::default line 86)
[2016-01-14T00:13:53+00:00] INFO: service[redis] restarted
[2016-01-14T00:13:53+00:00] ERROR: Running exception handlers
[2016-01-14T00:13:53+00:00] ERROR: Exception handlers complete
[2016-01-14T00:13:53+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2016-01-14T00:13:53+00:00] ERROR: 

Chef::Mixin::Template::TemplateError (Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"') on line #2:

1: # THIS FILE IS MAINTAINED BY CHEF. DO NOT MODIFY AS IT WILL BE OVERWRITTEN.
2: <%= mongodb_config @config%>

/opt/aws/opsworks/releases/20151222151215_3431-20151222151215/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/node/immutable_collections.rb:146:in `delete_if'
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb3/libraries/mongodb3_helper.rb:12:in `compact'
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb3/libraries/mongodb3_helper.rb:12:in `block in compact'
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb3/libraries/mongodb3_helper.rb:12:in `delete_if'
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb3/libraries/mongodb3_helper.rb:12:in `compact'
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb3/libraries/mongodb3_helper.rb:5:in `mongodb_config'
(erubis):2:in `block in evaluate'
```

**Comment by dblock** [comment]
This smells similar or at least related to https://github.com/sunggun-yu/chef-mongodb3/issues/9.

**Comment by dblock** [comment]
This was fixed in https://github.com/chef/chef/commit/b741b87b81f82587800da5329b47cfd414b3301d.

**Comment by dblock** [comment]
Fix in https://github.com/sunggun-yu/chef-mongodb3/pull/22.
