### ISSUE TITLE
chef-mongodb3 dependency metachef throws error

### ISSUE THREAD

**Issue by sebfek** [sunggun-yu/chef-mongodb3#27]
I got following error when I add mongodb3 to my cookbooks dependency:
https://gist.github.com/sebfek/3ac539d7c597520b695a

I run chef 12.6 here, so I don't know if this metachef dependency is still compatible with the current chef version.

Any idea?

**Comment by wesleung** [comment]
Maybe related.  was getting Librarian errors too.  Even if recipe has no include_recipe "mongodb3::default", once cookbook "mongodb3" is added to Cheffile we get 
ERROR: Librarian::Error: Could not resolve the dependencies. 

```
$ grep mongodb3 Cheffile
cookbook "mongodb3"
$ knife solo cook  10.0.2.107 -o "recipe[test]" 
Running Chef on 10.0.2.107...
Checking Chef version...
Installing Librarian cookbooks...
ERROR: Librarian::Error: Could not resolve the dependencies.
$ knife -v
Chef: 11.18.12
```

Found the fix when I ran

```
librarian-chef install --verbose
```

Clashing on runit 1.5.11 to 1.7.0. Found out I was missing a the ".git" extension which then updated runit version and fixed the problem. 

```
cookbook "runit", :git => "https://github.com/hw-cookbooks/runit.git"
```

Hope this helps

**Comment by moos3** [comment]
is there a plan to fix this error? It only happens when I use chef-provisioning-aws. I wondering if there's a conflict between mongodb3 and chef-provisioning-aws

```
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default:
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/metachef/attributes/default.rb
==> default: ================================================================================
==> default:
==> default:
==> default: TypeError
==> default: ---------
==> default: no implicit conversion of String into Integer
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/metachef/attributes/default.rb:9:in `[]'
==> default:
==> default:   /var/chef/cache/cookbooks/metachef/attributes/default.rb:9:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/metachef/attributes/default.rb:
==> default:
==> default:
==> default:
==> default:   2:  default[:metachef][:conf_dir] = '/etc/metachef'
==> default:
==> default:   3:  default[:metachef][:log_dir]  = '/var/log/metachef'
==> default:   4:  default[:metachef][:home_dir] = '/etc/metachef'
==> default:
==> default:   5:
==> default:
==> default:   6:  default[:metachef][:user]     = 'root'
==> default:   7:
==> default:
==> default:   8:  # Request user account properties here.
==> default:   9>> default[:users]['root'][:primary_group] = value_for_platform(
==> default:
==> default:  10:    "openbsd"   => { "default" => "wheel" },
==> default:  11:    "freebsd"   => { "default" => "wheel" },
==> default:
==> default:  12:    "mac_os_x"  => { "default" => "wheel" },
==> default:
==> default:  13:    "default"   => "root"
==> default:  14:  )
==> default:
==> default:  15:
==> default:  16:  default[:announces] ||= Mash.new
==> default:
==> default:  17:
==> default:  18:  default[:discovers] ||= Mash.new
==> default:
==> default:
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
==> default:
==> default:
==> default:
==> default: Running handlers:
==> default: [2016-08-26T15:02:59+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default:
==> default: [2016-08-26T15:02:59+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 26 seconds
==> default: [2016-08-26T15:02:59+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-26T15:02:59+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-26T15:02:59+00:00] ERROR: no implicit conversion of String into Integer
==> default: [2016-08-26T15:02:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
